<?php

$oneOffSettingsTabs = array (
  1 =>  array (
    'altTemplate' =>    array (
      0 => 1,
      1 => 6,
2 => 7,
    ),
  ),
);

$oneOffSettingsCharts = array (
  'EXR.Q.H11..NRD0.A' =>  array (
    'dateTimeLabelFormats' =>    array (
      'year' => 'Q%Q-%Y',
    ),
    'options' =>    array (
      'mapRegion' => 'EUR',
    ),
    'data' => array('url' => "https://sdw-wsrest.ecb.europa.eu/service/data/EXR/Q.E02+H02.EUR+ATS+BEF+CYP+DEM+EEK+ESP+FIM+FRF+GRD+IEP+ITL+LTL+LUF+LVL+MTL+NLG+PTE+SIT+SKK.ERD0+NRD0.A?startPeriod=2000",
                    'sdwCodes' => array(
                            'EUR' => 'EXR.Q.E02.EUR.ERD0.A',
                            'BEL' => 'EXR.Q.H02.BEF.NRD0.A',
                            'DEU' => 'EXR.Q.H02.DEM.NRD0.A',
                            'EST' => 'EXR.Q.H02.EEK.NRD0.A',
                            'IRL' => 'EXR.Q.H02.IEP.NRD0.A',
                            'GRC' => 'EXR.Q.H02.GRD.NRD0.A',
                            'ESP' => 'EXR.Q.H02.ESP.NRD0.A',
                            'FRA' => 'EXR.Q.H02.FRF.NRD0.A',
                            'ITA' => 'EXR.Q.H02.ITL.NRD0.A',
                            'CYP' => 'EXR.Q.H02.CYP.NRD0.A',
                            'LVA' => 'EXR.Q.H02.LVL.NRD0.A',
                            'LTU' => 'EXR.Q.H02.LTL.NRD0.A',
                            'LUX' => 'EXR.Q.H02.LUF.NRD0.A',
                            'MLT' => 'EXR.Q.H02.MTL.NRD0.A',
                            'NLD' => 'EXR.Q.H02.NLG.NRD0.A',
                            'AUT' => 'EXR.Q.H02.ATS.NRD0.A',
                            'PRT' => 'EXR.Q.H02.PTE.NRD0.A',
                            'SVN' => 'EXR.Q.H02.SIT.NRD0.A',
                            'SVK' => 'EXR.Q.H02.SKK.NRD0.A',
                            'FIN' => 'EXR.Q.H02.FIM.NRD0.A',
                    )),
  ),
  'EXR.Q.H11..NRU1.A' =>  array (
    'dateTimeLabelFormats' =>    array (
      'year' => 'Q%Q-%Y',
    ),
    'options' =>    array (
      'mapRegion' => 'EUR',
    ),
    'data' => array('url' => "https://sdw-wsrest.ecb.europa.eu/service/data/EXR/Q.E02+H02.EUR+ATS+BEF+CYP+DEM+EEK+ESP+FIM+FRF+GRD+IEP+ITL+LTL+LUF+LVL+MTL+NLG+PTE+SIT+SKK.ERU1+NRU1.A?startPeriod=2000",
                    'sdwCodes' => array(
                            'EUR' => 'EXR.Q.E02.EUR.ERU1.A',
                            'BEL' => 'EXR.Q.H02.BEF.NRU1.A',
                            'DEU' => 'EXR.Q.H02.DEM.NRU1.A',
                            'EST' => 'EXR.Q.H02.EEK.NRU1.A',
                            'IRL' => 'EXR.Q.H02.IEP.NRU1.A',
                            'GRC' => 'EXR.Q.H02.GRD.NRU1.A',
                            'ESP' => 'EXR.Q.H02.ESP.NRU1.A',
                            'FRA' => 'EXR.Q.H02.FRF.NRU1.A',
                            'ITA' => 'EXR.Q.H02.ITL.NRU1.A',
                            'CYP' => 'EXR.Q.H02.CYP.NRU1.A',
                            'LVA' => 'EXR.Q.H02.LVL.NRU1.A',
                            'LTU' => 'EXR.Q.H02.LTL.NRU1.A',
                            'LUX' => 'EXR.Q.H02.LUF.NRU1.A',
                            'MLT' => 'EXR.Q.H02.MTL.NRU1.A',
                            'NLD' => 'EXR.Q.H02.NLG.NRU1.A',
                            'AUT' => 'EXR.Q.H02.ATS.NRU1.A',
                            'PRT' => 'EXR.Q.H02.PTE.NRU1.A',
                            'SVN' => 'EXR.Q.H02.SIT.NRU1.A',
                            'SVK' => 'EXR.Q.H02.SKK.NRU1.A',
                            'FIN' => 'EXR.Q.H02.FIM.NRU1.A',
                    )),
  ),
  'EXR.M.H10..NRC0.A' =>  array (
    'options' =>    array (
      'mapRegion' => 'EUR',
    ),
    'data' => array('url' => "https://sdw-wsrest.ecb.europa.eu/service/data/EXR/M.E03+H03.EUR+ATS+BEF+CYP+DEM+EEK+ESP+FIM+FRF+GRD+HRK+IEP+ITL+LTL+LUF+LVL+MTL+NLG+PTE+SIT+SKK.ERC0+NRC0.A?startPeriod=2000",
                    'sdwCodes' => array(
                            'EUR' => 'EXR.M.E03.EUR.ERC0.A',
                            'BEL' => 'EXR.M.H03.BEF.NRC0.A',
                            'DEU' => 'EXR.M.H03.DEM.NRC0.A',
                            'EST' => 'EXR.M.H03.EEK.NRC0.A',
                            'IRL' => 'EXR.M.H03.IEP.NRC0.A',
                            'HRV' => 'EXR.M.H03.HRK.NRC0.A',
                            'GRC' => 'EXR.M.H03.GRD.NRC0.A',
                            'ESP' => 'EXR.M.H03.ESP.NRC0.A',
                            'FRA' => 'EXR.M.H03.FRF.NRC0.A',
                            'ITA' => 'EXR.M.H03.ITL.NRC0.A',
                            'CYP' => 'EXR.M.H03.CYP.NRC0.A',
                            'LVA' => 'EXR.M.H03.LVL.NRC0.A',
                            'LTU' => 'EXR.M.H03.LTL.NRC0.A',
                            'LUX' => 'EXR.M.H03.LUF.NRC0.A',
                            'MLT' => 'EXR.M.H03.MTL.NRC0.A',
                            'NLD' => 'EXR.M.H03.NLG.NRC0.A',
                            'AUT' => 'EXR.M.H03.ATS.NRC0.A',
                            'PRT' => 'EXR.M.H03.PTE.NRC0.A',
                            'SVN' => 'EXR.M.H03.SIT.NRC0.A',
                            'SVK' => 'EXR.M.H03.SKK.NRC0.A',
                            'FIN' => 'EXR.M.H03.FIM.NRC0.A',
                    )),
  ),
);
